### ISSUE TITLE
Install creates undefined package

### ISSUE THREAD

**Issue by timothystone** [Ebsan/generator-jhipster-es-entity-reindexer#6]
Version 1.0.2
JHipster 7.9.3

Installed per instructions, `npm install -g generator-jhipster-es-entity-reindexer` then followed with `yo jhipster-es-entity-reindexer`

Classes were placed in `/src/main/java/undefined/{config,web/rest,service}`:

```shell
% pwd 
~/Development/monolith/src/main/java/undefined
% ls **/*
config/ApplicationProperties.java        service/ElasticsearchIndexService.java   web/rest/ElasticsearchIndexResource.java

config:
ApplicationProperties.java

service:
ElasticsearchIndexService.java

web:
rest

web/rest:
ElasticsearchIndexResource.java
```

**Comment by timothystone** [comment]
@Ebsan Regarding #5 and this issue, I've never written a JHipster Generator, but I've forked this and will, hopefully 🤞 , be sending a PR.

**Comment by timothystone** [comment]
Looks like this issue is rooted in the generator `index.js` at [L50](https://github.com/Ebsan/generator-jhipster-es-entity-reindexer/blob/e1366c61a6c0f80db58823bf059a3a0549d61a3c/generators/app/index.js#L50). There's a comment about "reading from `.yo-rc.json`" which seems appropriate as the JHipsterProperties class does not define these. The `application.yml` does not populate these on creation 🤔 either. Is reading the `.yo-rc.json` a target state or work in progress?

**Comment by Ebsan** [comment]
Hmm, yeah this is weird. For some reason packageFolder is no longer in the `.yo-rc.json`. I can't find out when they removed this from the generator.

**Comment by Ebsan** [comment]
Here's someone having the same issue: https://github.com/jhipster/generator-jhipster/issues/18656. I can't tell if it's a regression or not in the generator-jhipster codebase but I'll try to update our module to fix it.
